---
title: "Research"
output:
  html_document:
    theme: flatly

---

<link rel="stylesheet" href="papercss-master/src/styles.scss" type="text/css">


Below are descriptions of my ongoing research projects. My published work is listed on my CV, which can be found [here](mitchell_elder_cv.pdf).

<p style="color:Gainsboro;font-size:150%;"> <em> Book Project </em></p>

<b> The Political Resource Curse in Eastern Coal Country </b> (Book Project)

For more than 100 years, the coal industry has dominated the economy and politics of mining areas in Appalachia and the Illinois Basin. This project documents how single-industry dominance shaped local governments in mining areas and traces the long-term consequences of captured, low-capacity institutions for modern political behavior. A paper drawing on material from the book project is [available here](jmp_mitchellelder.pdf). 

<p style="color:Gainsboro;font-size:150%;"> <em> Related Working Papers </em></p>

<b> Geographic Identity </b> (with Hans Lueders)

In a working paper, we develop a concept of geographic identity, or the extent to which a place is a part of an individual's self-concept. Several large surveys conducted in the United States and Europe suggest these feelings of attachment are related to political trust, engagement, and attitudes. A draft of this paper is available upon request.


<b> Political Corruption </b>

This project draws on a dataset collected for my book project that exhaustively lists people charged with crimes related to official corruption by the DOJ since 2000 in the region of the book's focus. A first working paper pairs this data with a large geocoded survey to understand the relationship between historical corruption and citizens' perceptions of it; a draft is available upon request. An ongoing data collection effort is seeking to expand this dataset to cover the entire United States.


<p style="color:Gainsboro;font-size:150%;"> <em> Political Knowledge and Participation </em></p>


<b> Journalist and Public Perceptions of Polarization </b> (with Neil O'Brian)

We demonstrate that Americans overestimate polarization between social groups on matters of group-related public policy, jut as they do polarization between partisans. We argue these perceptions are related to media portrayals. Using a large survey of political news producers, we demonstrate that political journalists, like the mass public, overrestimate group polarization. A draft of this paper is [available here](perceptions_draft.pdf). 



<b> Race and Participation in Small Groups </b>

In a series of papers with Tali Mendelberg and Christopher Karpowitz, we draw on 500 mock jury deliberations to study how participants of different racial backgrounds make their voices heard in discussions and their opinions reflected in group decisions. One paper in this line (with David Ribar) is published at the [Journal of Politics](https://www.journals.uchicago.edu/doi/full/10.1086/726946). A second working paper is [available here](jury_deliberation.pdf). 



<b> Psychological power and political participation </b>

This project explores the political implications of feeling powerful. Evidence from several large, high-quality surveys suggests that people who feel in control of what happens in their lives participate in politics at higher rates. Using panel data and survey experiments, I shed light on whether this relationship is causal. Paper available upon request.


<p style="color:Gainsboro;font-size:150%;"> <em> Methods for Survey Research </em></p>

<b> Accuracy of Survey Measures </b> (with Lisanne Wichgers, LinChiat Chang, David Chapman, Jon A. Krosnick, Matt Berent, Elaine Albertson, and Elizabeth Quinlan)

Much research on political behavior relies on self-reports from survey respondents. Yet some remain skeptical that self-reports are valid measures of individuals' attributes. This paper gathers evidence from several hundred papers that report the relationship between self-reported and "objective" (i.e. non-self-reported) measures of the same attribute. A draft of this paper is available upon request.

<b> Measuring Sexism in Diverse Samples </b> (with Matthew Hayes)

Attitudes about gender are consistently related to important political outcomes. But in this paper, we show that several common measures of gender attitudes fail to predict outcomes among Black Americans as well as they do among white Americans. We explore the reasons for this difference. A draft of this paper is available upon request.

<p style="color:Gainsboro;font-size:150%;"> <em> Health and Politics </em></p>

<b> Political Attitudes and Health Outcomes </b> (with Neil O'Brian)

Many Americans---especially conservatives---are losing trust in important social institutions. Recently, some conservatives have come to mistrust the medical establishment, and even their own personal doctors. We document the consequences of this loss of trust for medical outcomes. A draft of the first paper in this project is available upon request.


